# Generated by Django 2.0.6 on 2018-10-02 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20180914_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Profile')),
            ],
        ),
    ]
