# Generated by Django 2.0.6 on 2018-09-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='login/static/login/storage')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='login/static/login/storage'),
        ),
        migrations.AddField(
            model_name='user_file',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Profile'),
        ),
    ]
