# Generated by Django 2.0.6 on 2018-09-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180914_1251'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.Event'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Profile'),
        ),
    ]
